name: resources_gen
description: A simple command-line application.
version: 1.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  path: ^1.8.0
  http: ^0.13.3
  archive: ^3.1.2


dev_dependencies:
  pedantic: ^1.10.0
